// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDr-QhXWj05Z8kVO84Eljwdf2hz9VLd4',
    appId: '1:787698654160:web:0fc1c4247d6f2af47d77d5',
    messagingSenderId: '787698654160',
    projectId: 'evverse-33d02',
    authDomain: 'evverse-33d02.firebaseapp.com',
    storageBucket: 'evverse-33d02.firebasestorage.app',
    measurementId: 'G-FL5G18TB6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXiffWcNoWxGpUC8KFVKT-NhlCWk38Q70',
    appId: '1:787698654160:android:2a11103f122ea0fb7d77d5',
    messagingSenderId: '787698654160',
    projectId: 'evverse-33d02',
    storageBucket: 'evverse-33d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcPMs3Y6baKDmEUpKpkyP9D4oXYYFnI4',
    appId: '1:787698654160:ios:34ca2e24b142a5fc7d77d5',
    messagingSenderId: '787698654160',
    projectId: 'evverse-33d02',
    storageBucket: 'evverse-33d02.firebasestorage.app',
    androidClientId: '787698654160-6l9dspoqcn9raldisoj830i0kdlibgvc.apps.googleusercontent.com',
    iosClientId: '787698654160-349hpd547thdj02fbretgldbhk1gpb22.apps.googleusercontent.com',
    iosBundleId: 'com.example.evverseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcPMs3Y6baKDmEUpKpkyP9D4oXYYFnI4',
    appId: '1:787698654160:ios:34ca2e24b142a5fc7d77d5',
    messagingSenderId: '787698654160',
    projectId: 'evverse-33d02',
    storageBucket: 'evverse-33d02.firebasestorage.app',
    androidClientId: '787698654160-6l9dspoqcn9raldisoj830i0kdlibgvc.apps.googleusercontent.com',
    iosClientId: '787698654160-349hpd547thdj02fbretgldbhk1gpb22.apps.googleusercontent.com',
    iosBundleId: 'com.example.evverseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeDr-QhXWj05Z8kVO84Eljwdf2hz9VLd4',
    appId: '1:787698654160:web:c28f91206bc0afeb7d77d5',
    messagingSenderId: '787698654160',
    projectId: 'evverse-33d02',
    authDomain: 'evverse-33d02.firebaseapp.com',
    storageBucket: 'evverse-33d02.firebasestorage.app',
    measurementId: 'G-Q1T41HVJE8',
  );
}
